### ISSUE TITLE
ignorFile isn't working in j.sal.fs.copyDirTree

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/core9#188] opened 2018-01-31 14:45 UTC
```python
In [20]: rm -rf /tmp/test2

In [21]: j.sal.fs.copyDirTree('/tmp/test1', '/tmp/test2', ignorefiles=['test1File'])

In [22]: ls /tmp/test2
test1File  test2/

```

**Comment by rkhamis** [comment] 2018-02-11 08:05
duplicate of https://github.com/Jumpscale/core9/issues/187

**Closed by rkhamis** 2018-02-11 08:05 UTC
Labels: type_bug
